/* pos ve kurum txn işlemlerinde kullanılacak tabloya ön bilgiler */

INSERT INTO  PAYMENT_ACTION_TYPE  (ID,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER,CODE,NAME,INFO,SYSTEM,ISACTIVE,WEIGHT ) 
 VALUES (1,'2010-09-01','2010-09-01','tekir','tekir','SATIŞ','SATIŞ İŞLEMİ',null,true,true,10);

INSERT INTO  PAYMENT_ACTION_TYPE  (ID,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER,CODE,NAME,INFO,SYSTEM,ISACTIVE,WEIGHT ) 
 VALUES (2,'2010-09-01','2010-09-01','tekir','tekir','ALIŞ','ALIŞ İŞLEMİ',null,true,true,10);

INSERT INTO  PAYMENT_ACTION_TYPE  (ID,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER,CODE,NAME,INFO,SYSTEM,ISACTIVE,WEIGHT ) 
 VALUES (3,'2010-09-01','2010-09-01','tekir','tekir','ÖDEME','ÖDEME İŞLEMİ',null,true,true,10);

INSERT INTO  PAYMENT_ACTION_TYPE  (ID,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER,CODE,NAME,INFO,SYSTEM,ISACTIVE,WEIGHT ) 
 VALUES (4,'2010-09-01','2010-09-01','tekir','tekir','GERİ ÖDEME','GERİ ÖDEME İŞLEMİ',null,true,true,10);

INSERT INTO  PAYMENT_ACTION_TYPE  (ID,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER,CODE,NAME,INFO,SYSTEM,ISACTIVE,WEIGHT ) 
 VALUES (5,'2010-09-01','2010-09-01','tekir','tekir','İADE','İADE İŞLEMİ',null,true,true,10);

INSERT INTO  PAYMENT_ACTION_TYPE  (ID,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER,CODE,NAME,INFO,SYSTEM,ISACTIVE,WEIGHT ) 
 VALUES (6,'2010-09-01','2010-09-01','tekir','tekir','POS KOM','POS KOMİSYON ORANI',null,false,true,10);

INSERT INTO  PAYMENT_ACTION_TYPE  (ID,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER,CODE,NAME,INFO,SYSTEM,ISACTIVE,WEIGHT ) 
 VALUES (7,'2010-09-01','2010-09-01','tekir','tekir','POS HİZ','POS HİZMET/SERVİS KOMİSYON ORANI',null,false,true,10);

INSERT INTO  PAYMENT_ACTION_TYPE  (ID,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER,CODE,NAME,INFO,SYSTEM,ISACTIVE,WEIGHT ) 
 VALUES (8,'2010-09-01','2010-09-01','tekir','tekir','POS PEŞİN','POS PEŞİN ÖDÜL KOMİSYON ORANI',null,false,true,10);

INSERT INTO  PAYMENT_ACTION_TYPE  (ID,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER,CODE,NAME,INFO,SYSTEM,ISACTIVE,WEIGHT ) 
 VALUES (9,'2010-09-01','2010-09-01','tekir','tekir','POS TAKSİT','POS TAKSİT ÖDÜL KOMİSYON ORANI',null,false,true,10);

INSERT INTO  PAYMENT_ACTION_TYPE  (ID,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER,CODE,NAME,INFO,SYSTEM,ISACTIVE,WEIGHT ) 
 VALUES (10,'2010-09-01','2010-09-01','tekir','tekir','POS PUAN','POS PUAN ÖDÜL KOMİSYON ORANI',null,false,true,10);

INSERT INTO  PAYMENT_ACTION_TYPE  (ID,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER,CODE,NAME,INFO,SYSTEM,ISACTIVE,WEIGHT ) 
 VALUES (11,'2010-09-01','2010-09-01','tekir','tekir','SGK KATKI','SGK KATKI PAYI',null,false,true,10);

INSERT INTO  PAYMENT_ACTION_TYPE  (ID,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER,CODE,NAME,INFO,SYSTEM,ISACTIVE,WEIGHT ) 
 VALUES (12,'2010-09-01','2010-09-01','tekir','tekir','MÜŞKATKI-0','MÜŞTERİ KATKI PAYI %0',null,false,true,10);

INSERT INTO  PAYMENT_ACTION_TYPE  (ID,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER,CODE,NAME,INFO,SYSTEM,ISACTIVE,WEIGHT ) 
 VALUES (13,'2010-09-01','2010-09-01','tekir','tekir','MÜŞKATKI-10','MÜŞTERİ KATKI PAYI %10',null,false,true,10);

INSERT INTO  PAYMENT_ACTION_TYPE  (ID,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER,CODE,NAME,INFO,SYSTEM,ISACTIVE,WEIGHT ) 
 VALUES (14,'2010-09-01','2010-09-01','tekir','tekir','MÜŞKATKI-20','MÜŞTERİ KATKI PAYI %20',null,false,true,10);

INSERT INTO  PAYMENT_ACTION_TYPE  (ID,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER,CODE,NAME,INFO,SYSTEM,ISACTIVE,WEIGHT ) 
 VALUES (15,'2010-09-01','2010-09-01','tekir','tekir','SGK PRİM','SGK İŞVEREN PAYI PRİM',null,false,true,10);

INSERT INTO  PAYMENT_ACTION_TYPE  (ID,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER,CODE,NAME,INFO,SYSTEM,ISACTIVE,WEIGHT ) 
 VALUES (16,'2010-09-01','2010-09-01','tekir','tekir','SGK İŞSİZ','SGK İŞVEREN PAYI İŞSİZLİK PRİMİ',null,false,true,10);

INSERT INTO  PAYMENT_ACTION_TYPE  (ID,CREATE_DATE,UPDATE_DATE,CREATE_USER,UPDATE_USER,CODE,NAME,INFO,SYSTEM,ISACTIVE,WEIGHT ) 
 VALUES (17,'2010-09-01','2010-09-01','tekir','tekir','DAMGA V','DAMGA VERGİSİ',null,false,true,10);

INSERT INTO hibernate_sequences (SEQUENCE_NAME, SEQUENCE_NEXT_HI_VALUE) VALUES ('PAYMENT_ACTION_TYPE', 1);
 