package tr.gov.tubitak.protobuf;

//Generated by the protocol buffer compiler.  DO NOT EDIT!
//source: test.proto

public final class CatProto {
private CatProto() {}
public static void registerAllExtensions(
   com.google.protobuf.ExtensionRegistry registry) {
}
public interface CatOrBuilder extends
   // @@protoc_insertion_point(interface_extends:Cat)
   com.google.protobuf.MessageOrBuilder {

 /**
  * <code>optional int32 age = 1;</code>
  */
 boolean hasAge();
 /**
  * <code>optional int32 age = 1;</code>
  */
 int getAge();

 /**
  * <code>optional string name = 2;</code>
  */
 boolean hasName();
 /**
  * <code>optional string name = 2;</code>
  */
 java.lang.String getName();
 /**
  * <code>optional string name = 2;</code>
  */
 com.google.protobuf.ByteString
     getNameBytes();
}
/**
* Protobuf type {@code Cat}
*/
public static final class Cat extends
   com.google.protobuf.GeneratedMessage implements
   // @@protoc_insertion_point(message_implements:Cat)
   CatOrBuilder {
 // Use Cat.newBuilder() to construct.
 private Cat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
   super(builder);
   this.unknownFields = builder.getUnknownFields();
 }
 private Cat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

 private static final Cat defaultInstance;
 public static Cat getDefaultInstance() {
   return defaultInstance;
 }

 public Cat getDefaultInstanceForType() {
   return defaultInstance;
 }

 private final com.google.protobuf.UnknownFieldSet unknownFields;
 @java.lang.Override
 public final com.google.protobuf.UnknownFieldSet
     getUnknownFields() {
   return this.unknownFields;
 }
 private Cat(
     com.google.protobuf.CodedInputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws com.google.protobuf.InvalidProtocolBufferException {
   initFields();
   int mutable_bitField0_ = 0;
   com.google.protobuf.UnknownFieldSet.Builder unknownFields =
       com.google.protobuf.UnknownFieldSet.newBuilder();
   try {
     boolean done = false;
     while (!done) {
       int tag = input.readTag();
       switch (tag) {
         case 0:
           done = true;
           break;
         default: {
           if (!parseUnknownField(input, unknownFields,
                                  extensionRegistry, tag)) {
             done = true;
           }
           break;
         }
         case 8: {
           bitField0_ |= 0x00000001;
           age_ = input.readInt32();
           break;
         }
         case 18: {
           com.google.protobuf.ByteString bs = input.readBytes();
           bitField0_ |= 0x00000002;
           name_ = bs;
           break;
         }
       }
     }
   } catch (com.google.protobuf.InvalidProtocolBufferException e) {
     throw e.setUnfinishedMessage(this);
   } catch (java.io.IOException e) {
     throw new com.google.protobuf.InvalidProtocolBufferException(
         e.getMessage()).setUnfinishedMessage(this);
   } finally {
     this.unknownFields = unknownFields.build();
     makeExtensionsImmutable();
   }
 }
 public static final com.google.protobuf.Descriptors.Descriptor
     getDescriptor() {
   return CatProto.internal_static_Cat_descriptor;
 }

 protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
     internalGetFieldAccessorTable() {
   return CatProto.internal_static_Cat_fieldAccessorTable
       .ensureFieldAccessorsInitialized(
           CatProto.Cat.class, CatProto.Cat.Builder.class);
 }

 public static com.google.protobuf.Parser<Cat> PARSER =
     new com.google.protobuf.AbstractParser<Cat>() {
   public Cat parsePartialFrom(
       com.google.protobuf.CodedInputStream input,
       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
       throws com.google.protobuf.InvalidProtocolBufferException {
     return new Cat(input, extensionRegistry);
   }
 };

 @java.lang.Override
 public com.google.protobuf.Parser<Cat> getParserForType() {
   return PARSER;
 }

 private int bitField0_;
 public static final int AGE_FIELD_NUMBER = 1;
 private int age_;
 /**
  * <code>optional int32 age = 1;</code>
  */
 public boolean hasAge() {
   return ((bitField0_ & 0x00000001) == 0x00000001);
 }
 /**
  * <code>optional int32 age = 1;</code>
  */
 public int getAge() {
   return age_;
 }

 public static final int NAME_FIELD_NUMBER = 2;
 private java.lang.Object name_;
 /**
  * <code>optional string name = 2;</code>
  */
 public boolean hasName() {
   return ((bitField0_ & 0x00000002) == 0x00000002);
 }
 /**
  * <code>optional string name = 2;</code>
  */
 public java.lang.String getName() {
   java.lang.Object ref = name_;
   if (ref instanceof java.lang.String) {
     return (java.lang.String) ref;
   } else {
     com.google.protobuf.ByteString bs = 
         (com.google.protobuf.ByteString) ref;
     java.lang.String s = bs.toStringUtf8();
     if (bs.isValidUtf8()) {
       name_ = s;
     }
     return s;
   }
 }
 /**
  * <code>optional string name = 2;</code>
  */
 public com.google.protobuf.ByteString
     getNameBytes() {
   java.lang.Object ref = name_;
   if (ref instanceof java.lang.String) {
     com.google.protobuf.ByteString b = 
         com.google.protobuf.ByteString.copyFromUtf8(
             (java.lang.String) ref);
     name_ = b;
     return b;
   } else {
     return (com.google.protobuf.ByteString) ref;
   }
 }

 private void initFields() {
   age_ = 0;
   name_ = "";
 }
 private byte memoizedIsInitialized = -1;
 public final boolean isInitialized() {
   byte isInitialized = memoizedIsInitialized;
   if (isInitialized == 1) return true;
   if (isInitialized == 0) return false;

   memoizedIsInitialized = 1;
   return true;
 }

 public void writeTo(com.google.protobuf.CodedOutputStream output)
                     throws java.io.IOException {
   getSerializedSize();
   if (((bitField0_ & 0x00000001) == 0x00000001)) {
     output.writeInt32(1, age_);
   }
   if (((bitField0_ & 0x00000002) == 0x00000002)) {
     output.writeBytes(2, getNameBytes());
   }
   getUnknownFields().writeTo(output);
 }

 private int memoizedSerializedSize = -1;
 public int getSerializedSize() {
   int size = memoizedSerializedSize;
   if (size != -1) return size;

   size = 0;
   if (((bitField0_ & 0x00000001) == 0x00000001)) {
     size += com.google.protobuf.CodedOutputStream
       .computeInt32Size(1, age_);
   }
   if (((bitField0_ & 0x00000002) == 0x00000002)) {
     size += com.google.protobuf.CodedOutputStream
       .computeBytesSize(2, getNameBytes());
   }
   size += getUnknownFields().getSerializedSize();
   memoizedSerializedSize = size;
   return size;
 }

 private static final long serialVersionUID = 0L;
 @java.lang.Override
 protected java.lang.Object writeReplace()
     throws java.io.ObjectStreamException {
   return super.writeReplace();
 }

 public static CatProto.Cat parseFrom(
     com.google.protobuf.ByteString data)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return PARSER.parseFrom(data);
 }
 public static CatProto.Cat parseFrom(
     com.google.protobuf.ByteString data,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return PARSER.parseFrom(data, extensionRegistry);
 }
 public static CatProto.Cat parseFrom(byte[] data)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return PARSER.parseFrom(data);
 }
 public static CatProto.Cat parseFrom(
     byte[] data,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return PARSER.parseFrom(data, extensionRegistry);
 }
 public static CatProto.Cat parseFrom(java.io.InputStream input)
     throws java.io.IOException {
   return PARSER.parseFrom(input);
 }
 public static CatProto.Cat parseFrom(
     java.io.InputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws java.io.IOException {
   return PARSER.parseFrom(input, extensionRegistry);
 }
 public static CatProto.Cat parseDelimitedFrom(java.io.InputStream input)
     throws java.io.IOException {
   return PARSER.parseDelimitedFrom(input);
 }
 public static CatProto.Cat parseDelimitedFrom(
     java.io.InputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws java.io.IOException {
   return PARSER.parseDelimitedFrom(input, extensionRegistry);
 }
 public static CatProto.Cat parseFrom(
     com.google.protobuf.CodedInputStream input)
     throws java.io.IOException {
   return PARSER.parseFrom(input);
 }
 public static CatProto.Cat parseFrom(
     com.google.protobuf.CodedInputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws java.io.IOException {
   return PARSER.parseFrom(input, extensionRegistry);
 }

 public static Builder newBuilder() { return Builder.create(); }
 public Builder newBuilderForType() { return newBuilder(); }
 public static Builder newBuilder(CatProto.Cat prototype) {
   return newBuilder().mergeFrom(prototype);
 }
 public Builder toBuilder() { return newBuilder(this); }

 @java.lang.Override
 protected Builder newBuilderForType(
     com.google.protobuf.GeneratedMessage.BuilderParent parent) {
   Builder builder = new Builder(parent);
   return builder;
 }
 /**
  * Protobuf type {@code Cat}
  */
 public static final class Builder extends
     com.google.protobuf.GeneratedMessage.Builder<Builder> implements
     // @@protoc_insertion_point(builder_implements:Cat)
     CatProto.CatOrBuilder {
   public static final com.google.protobuf.Descriptors.Descriptor
       getDescriptor() {
     return CatProto.internal_static_Cat_descriptor;
   }

   protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
       internalGetFieldAccessorTable() {
     return CatProto.internal_static_Cat_fieldAccessorTable
         .ensureFieldAccessorsInitialized(
             CatProto.Cat.class, CatProto.Cat.Builder.class);
   }

   // Construct using CatProto.Cat.newBuilder()
   private Builder() {
     maybeForceBuilderInitialization();
   }

   private Builder(
       com.google.protobuf.GeneratedMessage.BuilderParent parent) {
     super(parent);
     maybeForceBuilderInitialization();
   }
   private void maybeForceBuilderInitialization() {
     if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
     }
   }
   private static Builder create() {
     return new Builder();
   }

   public Builder clear() {
     super.clear();
     age_ = 0;
     bitField0_ = (bitField0_ & ~0x00000001);
     name_ = "";
     bitField0_ = (bitField0_ & ~0x00000002);
     return this;
   }

   public Builder clone() {
     return create().mergeFrom(buildPartial());
   }

   public com.google.protobuf.Descriptors.Descriptor
       getDescriptorForType() {
     return CatProto.internal_static_Cat_descriptor;
   }

   public CatProto.Cat getDefaultInstanceForType() {
     return CatProto.Cat.getDefaultInstance();
   }

   public CatProto.Cat build() {
     CatProto.Cat result = buildPartial();
     if (!result.isInitialized()) {
       throw newUninitializedMessageException(result);
     }
     return result;
   }

   public CatProto.Cat buildPartial() {
     CatProto.Cat result = new CatProto.Cat(this);
     int from_bitField0_ = bitField0_;
     int to_bitField0_ = 0;
     if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
       to_bitField0_ |= 0x00000001;
     }
     result.age_ = age_;
     if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
       to_bitField0_ |= 0x00000002;
     }
     result.name_ = name_;
     result.bitField0_ = to_bitField0_;
     onBuilt();
     return result;
   }

   public Builder mergeFrom(com.google.protobuf.Message other) {
     if (other instanceof CatProto.Cat) {
       return mergeFrom((CatProto.Cat)other);
     } else {
       super.mergeFrom(other);
       return this;
     }
   }

   public Builder mergeFrom(CatProto.Cat other) {
     if (other == CatProto.Cat.getDefaultInstance()) return this;
     if (other.hasAge()) {
       setAge(other.getAge());
     }
     if (other.hasName()) {
       bitField0_ |= 0x00000002;
       name_ = other.name_;
       onChanged();
     }
     this.mergeUnknownFields(other.getUnknownFields());
     return this;
   }

   public final boolean isInitialized() {
     return true;
   }

   public Builder mergeFrom(
       com.google.protobuf.CodedInputStream input,
       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
       throws java.io.IOException {
     CatProto.Cat parsedMessage = null;
     try {
       parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
     } catch (com.google.protobuf.InvalidProtocolBufferException e) {
       parsedMessage = (CatProto.Cat) e.getUnfinishedMessage();
       throw e;
     } finally {
       if (parsedMessage != null) {
         mergeFrom(parsedMessage);
       }
     }
     return this;
   }
   private int bitField0_;

   private int age_ ;
   /**
    * <code>optional int32 age = 1;</code>
    */
   public boolean hasAge() {
     return ((bitField0_ & 0x00000001) == 0x00000001);
   }
   /**
    * <code>optional int32 age = 1;</code>
    */
   public int getAge() {
     return age_;
   }
   /**
    * <code>optional int32 age = 1;</code>
    */
   public Builder setAge(int value) {
     bitField0_ |= 0x00000001;
     age_ = value;
     onChanged();
     return this;
   }
   /**
    * <code>optional int32 age = 1;</code>
    */
   public Builder clearAge() {
     bitField0_ = (bitField0_ & ~0x00000001);
     age_ = 0;
     onChanged();
     return this;
   }

   private java.lang.Object name_ = "";
   /**
    * <code>optional string name = 2;</code>
    */
   public boolean hasName() {
     return ((bitField0_ & 0x00000002) == 0x00000002);
   }
   /**
    * <code>optional string name = 2;</code>
    */
   public java.lang.String getName() {
     java.lang.Object ref = name_;
     if (!(ref instanceof java.lang.String)) {
       com.google.protobuf.ByteString bs =
           (com.google.protobuf.ByteString) ref;
       java.lang.String s = bs.toStringUtf8();
       if (bs.isValidUtf8()) {
         name_ = s;
       }
       return s;
     } else {
       return (java.lang.String) ref;
     }
   }
   /**
    * <code>optional string name = 2;</code>
    */
   public com.google.protobuf.ByteString
       getNameBytes() {
     java.lang.Object ref = name_;
     if (ref instanceof String) {
       com.google.protobuf.ByteString b = 
           com.google.protobuf.ByteString.copyFromUtf8(
               (java.lang.String) ref);
       name_ = b;
       return b;
     } else {
       return (com.google.protobuf.ByteString) ref;
     }
   }
   /**
    * <code>optional string name = 2;</code>
    */
   public Builder setName(
       java.lang.String value) {
     if (value == null) {
 throw new NullPointerException();
}
bitField0_ |= 0x00000002;
     name_ = value;
     onChanged();
     return this;
   }
   /**
    * <code>optional string name = 2;</code>
    */
   public Builder clearName() {
     bitField0_ = (bitField0_ & ~0x00000002);
     name_ = getDefaultInstance().getName();
     onChanged();
     return this;
   }
   /**
    * <code>optional string name = 2;</code>
    */
   public Builder setNameBytes(
       com.google.protobuf.ByteString value) {
     if (value == null) {
 throw new NullPointerException();
}
bitField0_ |= 0x00000002;
     name_ = value;
     onChanged();
     return this;
   }

   // @@protoc_insertion_point(builder_scope:Cat)
 }

 static {
   defaultInstance = new Cat(true);
   defaultInstance.initFields();
 }

 // @@protoc_insertion_point(class_scope:Cat)
}

private static final com.google.protobuf.Descriptors.Descriptor
 internal_static_Cat_descriptor;
private static
 com.google.protobuf.GeneratedMessage.FieldAccessorTable
   internal_static_Cat_fieldAccessorTable;

public static com.google.protobuf.Descriptors.FileDescriptor
   getDescriptor() {
 return descriptor;
}
private static com.google.protobuf.Descriptors.FileDescriptor
   descriptor;
static {
 java.lang.String[] descriptorData = {
   "\n\ntest.proto\" \n\003Cat\022\013\n\003age\030\001 \001(\005\022\014\n\004name" +
   "\030\002 \001(\tB\nB\010CatProto"
 };
 com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
     new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
       public com.google.protobuf.ExtensionRegistry assignDescriptors(
           com.google.protobuf.Descriptors.FileDescriptor root) {
         descriptor = root;
         return null;
       }
     };
 com.google.protobuf.Descriptors.FileDescriptor
   .internalBuildGeneratedFileFrom(descriptorData,
     new com.google.protobuf.Descriptors.FileDescriptor[] {
     }, assigner);
 internal_static_Cat_descriptor =
   getDescriptor().getMessageTypes().get(0);
 internal_static_Cat_fieldAccessorTable = new
   com.google.protobuf.GeneratedMessage.FieldAccessorTable(
     internal_static_Cat_descriptor,
     new java.lang.String[] { "Age", "Name", });
}

// @@protoc_insertion_point(outer_class_scope)
}
